### PR TITLE
Hotfix/datasets table filesize

### PR DESCRIPTION
**Pull request by henrikjohansson712**
## Description

Fixed datasets table column widths so that no text gets cut off, added side scroll, and fixed checkboxes

## Motivation

Requested

## Changes:

* Updated styling to use `min-width` for datasets table columns instead of `flex`
* Moved `justify-content` properties to general column classes to avoid repetetiveness
* Added `owerflow: scroll` property to table styling
* All colors are now retrieved from theme file
* Removed unused css
* Added `isAllSelected` method to datasets table component
* Added `indetereminate` and `checked` properties to 'select all' checkbox

## Tests included/Docs Updated?

- [x] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by lukegorman** [comment]
do we definitely want scroll bars?

**Comment by lukegorman** [comment]
image

**Comment by henrikjohansson712** [comment]
Did not see bars like that in any of my browsers. Just added it as a failsafe, so that information wouldn't disappear if you have a lot of columns and a small screen. I can get rid of the scroll.

**Comment by lukegorman** [comment]
actually i think that was a caching issue

**Pull request merged**
