### PR TITLE
Chore/enable angular strict mode

### PR DESCRIPTION
**Pull request by henrikjohansson712**
## Description

Enable Angular strict mode.

### Notes
1. Enabling TypeScript strict mode not possible due to the automatically generated LoopBack SDK, added betterer tests as a workaround. I suspect that the .betterer.results file will need to be removed if the SDK is updated, otherwise the tests might fail.
2. Custom theme is now located in *styles.scss* and *theme.scss* no longer exists.

## Motivation

Stricter checks on code to ensure good quality.

## Changes:

* Enable Angular strict mode.
* Add betterer tests to ensure that new code complies with TypeScript strict mode.
* Update custom theme to decrease compiled *styles.css* bundle size.
* Replace saturn-datepicker with angular material datepicker.
* Update eslint

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [x] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by nitrosx** [comment]
It looks good to me.
I tested on my machine and everything appears to work correctly.

**Review by nguyenlinhlinh — COMMENTED** [review]
Overall it looks good. I don't know much about angular theme and scss so I skipped them. I have only some small comments.
I am also impressed by how much the size of the files has shrunk and wonder how you managed to do that.
Development build before
Screenshot 2021-07-12 at 14 52 54
Development build on this branch
Screenshot 2021-07-20 at 14 02 26

**Comment by henrikjohansson712** [comment]
@nguyenlinhlinh Thanks for the suggestions, I've pushed the changes. Not really sure what it is that makes the main bundle so much smaller.

**Comment by nguyenlinhlinh** [comment]
I am suspecting that the removal of staturn date picker reduces the bundle size but I am not sure.

**Review by nguyenlinhlinh — APPROVED** [review]

**Review by stephan271 — APPROVED** [review]

**Pull request merged**
