### PR TITLE
Feature/als ci

### PR DESCRIPTION
**Pull request by dylanmcreynolds**
## Description

Add AL CI files to repository

## Motivation
Following the pattern existing CI patter, adding CI files for ALS to the  repository.

## Changes:

* Add CI/ALS directory with environments and overrides for dev (local), staging server and production server build environemnts. Contains a makefile to build and push containers.
* Add references to the three environemnts to angular.json

### CODE REVIEW

**Comment by stephan271** [comment]
@dylanmcreynolds could you have a look at the failing tests ?

**Comment by dylanmcreynolds** [comment]
@stephan271 I reverted the package-lock.json change, which should fix one of the issues. However, I have to wait for someone to approve running workflows as a first-time contributor. I think there might still be an issue with docker-hub and secrets.

**Comment by dylanmcreynolds** [comment]
@stephan271 I added docker secrets, hopefully this runs now.

**Comment by stephan271** [comment]
The E2E tests seem to require a docker login. @henrikjohansson712 do you know how to fix this ?

**Comment by henrikjohansson712** [comment]
I've updated the ci e2e workflow so that it no longer uses docker hub. @dylanmcreynolds if you sync your fork and pull in the changes to this branch, the e2e tests should work

**Comment by dylanmcreynolds** [comment]
@henrikjohansson712 Thanks. I was kinda hoping to get the credentials to work...I'd like to investigate using Dockerhub to build my containers for Scicat. But let's get this PR going.

**Comment by henrikjohansson712** [comment]
@dylanmcreynolds I don't think it would have worked even with your credentials set up, because you would also need to have permissions to push to the dacat/catanie repo on DockerHub, and we aren't allowed to give permission to any more accounts, since we're on a free plan.

We use GitLab pipelines to build our docker images used for deployment, so you could add a hook to trigger your own GitLab pipeline in [ci.yml](https://github.com/SciCatProject/catanie/blob/develop/.github/workflows/ci.yml). I would be happy to share our GitLab CI file with you, to get you started.

**Pull request merged**
