### PR TITLE
Feature/share datasets

### PR DESCRIPTION
**Pull request by henrikjohansson712**
## Description

Makes it possible to share datasets with other SciCat users through their email. This is done through the batch view, where a user can type in one or more email addresses and share the selected datasets with these users. If an email address isn't connected to a current SciCat user, an error is thrown. Once a dataset has been shared with a user, the username of this user is listed in the "Shared With" filed in the dataset detail view. The dataset can then be unshared by clicking the "X" next to the username.

Further things to add to this feature is probably a limitation on which proposal members that should be able to share and unshare a dataset.

Depends on catamel [#482](https://github.com/SciCatProject/catamel/pull/482).

## Motivation:

See issue #808

## Changes:

* Add share button and dialog to batch view

## Tests included/Docs Updated?

- [x] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [x] Toggle added for new features?
- [x] Requires update of catamel API?

### CODE REVIEW

**Comment by nguyenlinhlinh** [comment]
I am trying this feature out by checking out this branch in catanie and catamel. Do I need to do something more in order for this to work? I get this error "**The email address is not connected to a SciCat user**" eventhough the email I use is a Scicat user. The error I get from the backend is "**GET /api/v3/UserIdentities/findOne: Error: Unknown "UserIdentity" id "undefined**"

**Comment by henrikjohansson712** [comment]
@nguyenlinhlinh Shouldn't need anything else, it's just that right now the email address needs to be an exact match of what is stored in the database. So it might be that the email address in the database has some uppercase letters.

**Comment by nguyenlinhlinh** [comment]
@henrikjohansson712: Thank you for working with this.
I was able to find some of our test accounts in AD only and sometimes with the same test account (that was found before) I got the error that the email address is not connected. With the real user accounts it doesn't work but I assume that something is wrong in our configuration unless other facilities also have the same problem. 

I notice that after sharing, the dataset get a field Share With: 2054, 3749 which I don't know where they come from but I personally prefer to see the usernames as you showed in the meeting instead of number, since it is easier for the user to figure out which user it is at removing. 

Is it possible to add a configuration variable so that we can enable or disable this feature. We need to figure out how to deal with file access before we can allow user to use this feature. Nothing advance just a variable something like `sharingEnabled = true or false`  and then on the share button in batch view can be disabled depend on the variable `<button disable=!sharingEnabled >Share<button>`.

**Comment by henrikjohansson712** [comment]
@nguyenlinhlinh 
> I notice that after sharing, the dataset get a field Share With: 2054, 3749 which I don't know where they come from but I personally prefer to see the usernames as you showed in the meeting instead of number, since it is easier for the user to figure out which user it is at removing.

Thought it would be better to discuss this in the catamel pr, see: https://github.com/SciCatProject/catamel/pull/482#issuecomment-919179513

> Is it possible to add a configuration variable so that we can enable or disable this feature. We need to figure out how to deal with file access before we can allow user to use this feature. Nothing advance just a variable something like sharingEnabled = true or false and then on the share button in batch view can be disabled depend on the variable <button disable=!sharingEnabled >Share<button>.

You're right, that's probably a good idea. Thanks!

**Comment by nitrosx** [comment]
@henrikjohansson712: I just try to share one dataset with myself and when I view it I see the following:
Screenshot 2021-10-01 at 10 54 29

I was expecting to see my user name or email.

**Comment by nitrosx** [comment]
Now I shared also with @henrikjohansson712, and his username/email is shared correctly
Screenshot 2021-10-01 at 11 01 25

**Comment by nitrosx** [comment]
I checked in the database and here the dataset has the following info under sharedWith:
`  
"sharedWith": [
    "1ddc156f-0d46-3297-b03d-db47a68b03a7",
    "henrikjohansson"
  ],
`

@henrikjohansson712: should we prevent sharing with myself? Also, why when I shared with myself, it stored a uuid?

**Comment by nitrosx** [comment]
I would like to see the correct username or email listed under "Shared With" in the details section of the dataset page.

**Comment by henrikjohansson712** [comment]
@nitrosx Looks the `UserIdentity.externalId` field is a uuid for a few of our users. I guess it's better to use another field to populate the `Dataset.sharedWith` array, like `UserIdentity.profile.username`, since `UserIdentity.externalId` also caused issues for MAX IV.

@nguyenlinhlinh Would using `UserIdentity.profile.username` work for you?

**Comment by nguyenlinhlinh** [comment]
> @nguyenlinhlinh Would using `UserIdentity.profile.username` work for you?
With username our shows up like this "Linh Nguyen". It is ok but if you use this parameter for distinguish between user it might not work for us since this parameter it is not unique.

**Review by nguyenlinhlinh — APPROVED** [review]

**Review by stephan271 — APPROVED** [review]

**Pull request merged**
