### PR TITLE
Shared table for proposal dashboard

### PR DESCRIPTION
**Pull request by nguyenlinhlinh**
## Description
This PR solves issue #756 
## Motivation
See issue #756
## Fixes:
Fixed the filter issue
Screenshot 2021-05-06 at 11 10 55
## Changes:
- Using ShareTableComponent instead
- Removed "Author" column (Not sure how to get both firstname and lastname to show up in one column. Change in Share table is required to do that).
## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by stephan271** [comment]
I would add more columns, in particular  firstname and lastname in separate columns and the abstract

**Comment by nguyenlinhlinh** [comment]
Thank for the suggestions. I must be so tired today that I didn't realize that I can show them i separate column. My bad.

**Comment by stephan271** [comment]
No problem. Thanks for helping ! 
( And catch some sleep , dont risk your health !)

**Comment by nguyenlinhlinh** [comment]
I made the changes. However I skipped the abstract column because I think long texts use to break the styling and the user can still see abstract in detail page.
Screenshot 2021-05-06 at 14 52 33

**Comment by stephan271** [comment]
Okay, lets go for it. The initial problem (I think it was a search bug) is solved now ? Did you test ?

**Pull request merged**
