### PR TITLE
Show values in custom column

### PR DESCRIPTION
**Pull request by nguyenlinhlinh**
## Description
There are custom columns that show values in requested unit. This works for flat metadata but not nested. This PR adds support for nested metadata.
Screenshot 2021-09-15 at 09 55 53

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [x] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by stephan271** [comment]
@nguyenlinhlinh what is the status for this merge request ? There seem to be some issues. Do you need any feedback from me or Henrik before being able to address the failing checks ?

**Comment by nguyenlinhlinh** [comment]
@stephan271  I will take a look into this

**Comment by nguyenlinhlinh** [comment]
Hi @stephan271, now this PR is redo for reviewing/merging again

**Comment by stephan271** [comment]
Does not yet seem to work for our data: 
image

If you want we can have a zoom session later today, then I can show you how it looks on our side.

**Comment by nguyenlinhlinh** [comment]
@stephan271  Could it be that your data is save as {v: value, u: unit} instead? Yes we can talk over zoom. I am free the whole day.

**Comment by stephan271** [comment]
Yes it is in v,u format. Can this be supported as well ?

**Comment by nguyenlinhlinh** [comment]
@stephan271 yes, I can add support for that. I think it also need some changes in the search function in the backend to search using v and u. However it would be nice if you can migrate to values and unit :) so we a standard.

**Comment by stephan271** [comment]
I am afraid we currently have a mix of both. Changing to one standard would mean, to update thousands of datasets. So may be extending the "standard" to cover both cases is the more pragmatic way, especially since many of the raw data files (hdf5) also have the v/u syntax already, and those can not/will not be changed.

**Comment by nguyenlinhlinh** [comment]
@stephan271  I see, then it is easier to change in the code instead. could you try again to see if it works.

**Comment by stephan271** [comment]
Sorry, it does not yet work on my side. I get the following error in the browser console as soon as I select some of the quantities in the scientificMetadata section

> ERROR TypeError: dataset_r96.scientificMetadata is undefined
>     DatasetTableComponent_ng_template_47_ng_template_0_mat_cell_2_Template dataset-table.component.html:362
>     Angular 40
>     RxJS 5
>     Angular 9
> core.js:6479
>     Angular 14
>     RxJS 5
>     Angular 9
>

**Comment by nguyenlinhlinh** [comment]
@stephan271 hmm, it is difficult for me to debug when I don't see how the dataset looks like. Maybe we can talk over zoom when you have time. I am suspecting that the dataset doesn't have **scientificMetadata** field.  **dataset_r96** is strange I wonder where it comes from.

**Comment by nguyenlinhlinh** [comment]
Hi @stephan271, I have added the tooltip as you suggested. However, I don't know how to fix the failed unit test that complain about coverage. I ran the test locally and it worked for me.

**Comment by nguyenlinhlinh** [comment]
@stephan271 could we merge this one? I am going to create another PR for supporting multiple formats later when I have time.

**Pull request merged**
