### PR TITLE
Shared table styling

### PR DESCRIPTION
**Pull request by nguyenlinhlinh**
## Description
Styling the shared table.
## Changes:
- Added buttons for hide/show/clear filters 
- Separate the filters from header row
- Hide paginator range label on small screen
## Some pictures of the end result
Pic 1 & 2: Table on small screen
Screenshot 2021-07-20 at 08 39 05

Screenshot 2021-07-20 at 08 39 14
Pic 3: Table on large screen
Screenshot 2021-07-20 at 08 34 48

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

### CODE REVIEW

**Comment by stephan271** [comment]
To my eye Pic3 and Pic 4 look more pleasing

**Comment by henrikjohansson712** [comment]
I agree with @stephan271, looks nice and clean. Could you also try to make the icon on the top left in the header white?

**Comment by nguyenlinhlinh** [comment]
> Could you also try to make the icon on the top left in the header white?
Sure I can do that.

**Comment by nguyenlinhlinh** [comment]
@stephan271, Are there an easy way to clear all the filters (except the default ones) ? I tried to figure out how to do that but the code seems to be difficult so I don't want to do something I don't know.

**Comment by stephan271** [comment]
> @stephan271, Are there an easy way to clear all the filters (except the default ones) ? I tried to figure out how to do that but the code seems to be difficult so I don't want to do something I don't know.

I am afraid the answer is no for now. But I  assume it is not that hard to add... probably add a new function called resetFilters or similar to the https://github.com/SciCatProject/catanie/blob/develop/src/app/shared/modules/shared-table/shared-table.component.ts file and do something similar as in   reloadFilterExpressions()

**Comment by nguyenlinhlinh** [comment]
@stephan271 Thank for the advice. I tried to follow it by updating the allFilters and filterExpressions but it only clear the input in GUI and in the end I realized that changing the queryParams reloads the data and clear input fields so I change the queryParams instead. Please let me know if it is a bad way to do that.

**Comment by nitrosx** [comment]
@nguyenlinhlinh: nice work. I just tested this PR. Nice responsive design. 
I've notice that when you reset the filters, the table updates but the filters maintain the values.

**Comment by nitrosx** [comment]
Here is the image of the table after I cleared the filters
shared_table_filters_1

**Comment by nguyenlinhlinh** [comment]
@nitrosx I don't know why I didn't get notifications on your comments but I see them now. I will try to fix that.

**Comment by nguyenlinhlinh** [comment]
I am sorry for asking you (@nitrosx , @stephan271 , @henrikjohansson712 ) to take a look to this PR again because I have made some more changes due to the bug I found. 
The change since commit #1dda4f6 is replacing ElementRef for filter input with angular FormGroup and this leads to some small changes in other places.

**Review by stephan271 — APPROVED** [review]

**Comment by nguyenlinhlinh** [comment]
Is it ok if I merge this one :), @henrikjohansson712 ?

**Review by henrikjohansson712 — APPROVED** [review]
Go ahead!

**Pull request merged**
